[[navbar]]
	name = "About"
	identifier = "about"
	url = "/about/"
	weight = -2000
[[navbar]]
	name = "Events"
	identifier = "events"
	url = "/events/"
	weight = -1900
[[navbar]]
	name = "Chat"
	identifier = "chat"
	url = "https://mattermost.gsebelux.eu/"
	weight = -1800
[[navbar]]
	name = "Workgroups"
	identifier = "workgroups"
	url = "/workgroups/"
	weight = -1700
[[navbar]]
	parent = "workgroups"
	name = "Overview"
	url = "/workgroups/"
	weight = -3000
[[navbar]]
	parent = "workgroups"
	name = "Architecture & Innovation"
	url = "/workgroups/architectureinnovation/"
	weight = -2000
[[navbar]]
	parent = "workgroups"
	name = "DevOps & Automation"
	url = "/workgroups/devopsautomation/"
	weight = -1900
[[navbar]]
	parent = "workgroups"
	name = "Enterprise System Security"
	url = "/workgroups/enterprisesystemsecurity/"
	weight = -1800
[[navbar]]
	parent = "workgroups"
	name = "IMS and DB2 Systems"
	url = "/workgroups/imsdb2"
	weight = -1700
[[navbar]]
	parent = "workgroups"
	name = "Large Users Management"
	url = "/workgroups/largeusermanagement"
	weight = -1600
[[navbar]]
	parent = "workgroups"
	name = "Middleware and Transaction Systems"
	url = "/workgroups/middlewaretransactionsystems/"
	weight = -1500
[[navbar]]
	parent = "workgroups"
	name = "Storage Management"
	url = "/workgroups/storagemanagement/"
	weight = -1400
[[navbar]]
	parent = "workgroups"
	name = "Young Professionals"
	url = "/workgroups/youngprofessionals/"
	weight = -1300
[[navbar]]
	parent = "workgroups"
	name = "Operating Systems"
	url = "/workgroups/operatingsystems"
	weight = -1200
[[navbar]]
	parent = "workgroups"
	name = "Regional Board Commitee"
	url = "/workgroups/regionalboardcommitee"
	weight = -100
